version: '3.7'
services:
  eposmol:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - Dockerfile
            - docker-compose-eposmol.yml
            - renv/
            - renv.lock
            - .Rprofile
    ports:
      - 3838:3838
    networks:
      - network
networks:
  network:
    driver: bridge
