---
title: "Examples for Empirical Lipid Point Score for Mass Spectrometry"
output:
  pdf_document: default
  html_document: default
---


```{r, echo=FALSE}
renv::install(c("tidyverse","readxl","lifs-tools/rgoslin"))
library(tidyverse)
library(readxl)
library(rgoslin)
```

```{r, echo=TRUE}
scoringScheme <- read_excel(
  path = file.path("data", "Table 1_mod.xlsx"),
  sheet = "Scoring scheme", 
  range = "A1:X30"
)
```

```{r}
scoringSchemeLong <- scoringScheme %>% 
  pivot_longer(
    cols=!Primary:Evidence, 
    names_to = "lipidClassification"
  )
scoringSchemeLong
```

## Example a

|               |                     |
| ------------- | ------------------- |
| Platform      | TQ EVOQ Elite       |
| Separation    | UHPLC               |
| MS Mode       | MRM                 |
| Ion Mode      | (+)                 |

```{r}
ex_a <- "Cer 18:1;O2/16:0"
ex_a_norm <- parseLipidNames(ex_a)
ex_a_norm
```

```{r}
ex_a_lc <- ex_a_norm[1, "Lipid.Maps.Category"]
nominalMassPos <- scoringSchemeLong %>% 
  filter(
    Primary=="MS1" & 
    Secondary=="Molecular properties" &
    Evidence=="Nominal mass" &  
    lipidClassification==ex_a_lc
  ) %>% 
  select(value)
separation <- scoringSchemeLong %>% 
  filter(
    Primary=="MS1" &
    Secondary=="Molecular properties" &  
    Evidence=="Chromatography (RT)" &  
    lipidClassification==ex_a_lc
  ) %>% 
  select(value)
headGroup <- scoringSchemeLong %>% 
  filter(
    Primary=="MS2" &
    Secondary=="CID fragments" &  
    Fragment=="LCF" &  
    Evidence=="Headgroup 1" &  
    lipidClassification==ex_a_lc
  ) %>% 
  select(value)
score <- sum(  
  nominalMassPos,
  separation,
  headGroup
)                                                                        
score
```
## Example b

|               |                     |
| ------------- | ------------------- |
| Platform      | QTrap 6500          |
| Separation    | NA                  |
| MS Mode       | Precursor Ion Scan  |
| Ion Mode      | (+) & (-)           |
```{r}
ex_b <- "Cer 18:1;O2/18:1"
ex_b_norm <- parseLipidNames(ex_b)
ex_b_norm
```

```{r}
ex_b_lipidCategory <- ex_b_norm[1, "Lipid.Maps.Category"]
nominalMassPos <- scoringSchemeLong %>% 
  filter(
    Primary=="MS1" & 
    Secondary=="Molecular properties" &
    Evidence=="Nominal mass" &  
    lipidClassification==ex_b_lipidCategory
  ) %>% 
  select(value)
headGroup1Pos <- scoringSchemeLong %>% 
  filter(
    Primary=="MS2" &
    Secondary=="CID fragments" &  
    Fragment=="LCF" &  
    Evidence=="Headgroup 1" &  
    lipidClassification==ex_b_lipidCategory
  ) %>% 
  select(value)
nominalMassNeg <- scoringSchemeLong %>% 
  filter(
    Primary=="MS1" & 
    Secondary=="Molecular properties" &
    Evidence=="Nominal mass" &  
    lipidClassification==ex_b_lipidCategory
  ) %>% 
  select(value)
headGroup1Neg <- scoringSchemeLong %>% 
  filter(
    Primary=="MS2" &
    Secondary=="CID fragments" &  
    Fragment=="LCF" &  
    Evidence=="Headgroup 2" &  
    lipidClassification==ex_b_lipidCategory
  ) %>% 
  select(value)
fa1Neg <- scoringSchemeLong %>% 
  filter(
    Primary=="MS2" &
    Secondary=="CID fragments" &  
    Fragment=="MLF" &  
    Evidence=="Fatty acyl 1-1" &  
    lipidClassification==ex_b_lipidCategory
  ) %>% 
  select(value)
score <- sum(  
  nominalMassPos,
  headGroup1Pos,
  nominalMassNeg,
  headGroup1Neg,
  fa1Neg
)                                                                        
score
```